# Numpy
Numerical Python
1. Allow several math operations
2. Faster operation

In [2]:
import numpy as np

In [9]:
# Example
from time import process_time
arr = [i for i in range(10000)]
st_time=process_time()
arr = [i+5 for i in arr]
end_time=process_time()
print(end_time-st_time)

np_arr = np.array([i for i in range(10000)])
st_time=process_time()
np_arr+=5
end_time=process_time()
print(end_time-st_time)

0.0
0.0


In [5]:
np_arr1 = np.array((1,2,3,4)) # use tuple or list doesn't matter as arg
np_arr2 = np.array([[1,2,3,4],[5,6,7,8]]) # default datatype is int
print(np_arr1.shape)
print(np_arr2.shape)

(4,)
(2, 4)


In [11]:
a=[(1,2,3),(4,5,6)]
b = np.array(a,dtype=float)
print(a) #comma separated
print(b) # no commas
#size =total elements, ndim=dimension, 2d here
print(b.shape, b.size, b.ndim, b.dtype)

[(1, 2, 3), (4, 5, 6)]
[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3) 6 2 float64


# Creating Arrays with Initial Placeholders

In [7]:
a = np.ones((2,4)) # shape provided
# a = np.zeroes((2,4))
print(a) # default float

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
b=np.full((3,5),2)
print(b) # default int

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [ ]:
# creating an identity matrix
c=np.eye(3) # deafult float
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# creating array with random values 1d, 2d by shape
d=np.random.random((3,4))
print(d) # float -> [0,1)

e=np.random.randint(2,15,(3,3))
print(e) # int -> [2,15)

[0.37157503 0.56420342 0.51369171 0.25932412]
[13  7  6]


In [15]:
# evenly spaced 1D array values -> specify number of values
d=np.linspace(10,40,6)
print(d) # float -> [10,40]

# evenly spaced 1D array values by steps
d=np.arange(10,40,6)
print(d) # int -> [10,40)

[10. 16. 22. 28. 34. 40.]
[10 16 22 28 34]


# Math operations on arrays


In [30]:
a1=[2,3,4]
a2=[5,6,7]
print(a1+a2) # concatenation happens

b1=np.array(a1)
b2=np.array(a2)
# shape should be equal
print(b1+b2) # Addition will happen,  -,*,/ can also be done

print(np.add(a1,a2)) # methods can be called on normal arrays also
print(np.subtract(b1,b2))

[2, 3, 4, 5, 6, 7]
[ 7  9 11]
[ 7  9 11]
[-3 -3 -3]


# Array Manipulation

In [34]:
arr=np.random.randint(10,20,(2,3))
print(arr)
print(arr.shape)

trans1=np.transpose(arr)
trans2=arr.T #same as above

print(trans1)
print(trans2)
print(trans1.shape)

[[18 13 13]
 [13 11 12]]
(2, 3)
[[18 13]
 [13 11]
 [13 12]]
[[18 13]
 [13 11]
 [13 12]]
(3, 2)


In [10]:
a=np.array([[2,3,4],[5,6,7]])
modified=a.reshape(3,2) # no. of elements should be exactly to fill the new shape completely
print(modified)

[[2 3]
 [4 5]
 [6 7]]
